/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Beranda;

import Connect.ConnectDB;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dell
 */
public class Cari extends javax.swing.JPanel {

     private Connection conn = (Connection) new ConnectDB().connect();
     
    private final Dashboard main;
    public Cari(Dashboard main) {
        initComponents();
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nikKar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        namaKar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        selectType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        allTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(30, 30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pencarian");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Nomor Induk Karyawan");

        nikKar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nikKar.setPreferredSize(new java.awt.Dimension(64, 50));

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cari");
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(0, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namaKar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        namaKar.setPreferredSize(new java.awt.Dimension(64, 50));
        namaKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Nama Karyawan");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("Cari Untuk :");

        selectType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        selectType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Absensi", "Cuti", "Gaji", "Lembur", "Resign" }));

        allTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Induk Karyawan", "Nama Karyawan", "Divisi", "Jabatan"
            }
        ));
        jScrollPane1.setViewportView(allTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 157, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 157, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nikKar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaKar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nikKar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaKar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: /* 
        
        
        /*    Absensi
            Cuti
            Gaji
            Lembur
            Resign
        */
        
        String selected = (String) selectType.getSelectedItem().toString();
        System.out.println("Ini Data : " + selected);
        
        switch(selected){
            case "Absensi":
                absenData();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void absenData(){
        
        //        ADD COLUMN TABLE MODEL
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("NIK");
        model.addColumn("NAMA");
        model.addColumn("STATUS");
        model.addColumn("KETENTUAN");   
        allTable.setModel(model);
                
        String nik = nikKar.getText();
        String nama = namaKar.getText();
          
        String sql = """
                        SELECT 
                            TK.NIK, 
                            TK.NAMA_KARYAWAN, TK.STATUS_KEHADIRAN, TK.KETERANGAN FROM TB_ABSEN TA
                        INNER JOIN TB_KARYAWAN  TK ON TA.ID_KARYAWAN = TK.ID_KARYAWAN
                        WHERE (TK.NIK IS NULL OR TK.NIK ='' OR UPPER(TK.ID_KARYAWAN) LIKE UPPER ('%' || ? || '%')) 
                        AND  (TK.NAMA_KARYAWAN IS NULL OR TK.NAMA_KARYAWAN = '' OR UPPER(TK.NAMA_KARYAWAN) LIKE UPPER ('%' || ? || '%'))
                        AND TA.STATUS_KEHADIRAN = ?
                     """;
        try{  
            PreparedStatement ps = (PreparedStatement) conn.prepareStatement(sql);
            ps.setString(1, nik);
            ps.setString(2, nama);
            
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                Object[] row = {
                    rs.getString("NIK"),
                    rs.getString("NAMA"),
                    rs.getString("STATUS"),
                    rs.getString("KETERANGAN"),
                };
//                ADD ROW TABLE MODEL
//                model.addRow(row);
            }
            rs.close();
            conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "koneksi Gagal");
        }
    }
    
    
    private void cutiData(){
         String sql = """
                        SELECT TK.NIK, TK.NAMA_KARYAWAN, TC.TANGGAL, TC.LAMA_CUTI FROM TB_CUTI TC
                        INNER JOIN TB_KARYAWAN  TK ON TC.ID_KARYAWAN = TK.ID_KARYAWAN
                        WHERE (TK.NIK IS NULL OR TK.NIK ='' OR UPPER(TK.ID_KARYAWAN) LIKE UPPER ('%' || ? || '%')) 
                        AND  (TK.NAMA_KARYAWAN IS NULL OR TK.NAMA_KARYAWAN = '' OR UPPER(TK.NAMA_KARYAWAN) LIKE UPPER ('%' || ? || '%'))
                     """;
         
    }
    
   
    private void namaKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaKar;
    private javax.swing.JTextField nikKar;
    private javax.swing.JComboBox<String> selectType;
    // End of variables declaration//GEN-END:variables
}
